config/routes.rb
Rails.application.routes.draw do
 devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :events
  resources :users, only: [:index, :edit, :update, :show]
  resources :orders, only: [:new, :create]
  resources :attendances
  # Defines the root path route ("/")
  root "welcome#index"
  

  namespace :admin do
    root to: 'admin#index'
  end
get "admin/index"


  namespace :admin do
    resources :users, only: [:index, :edit, :update, :destroy]
  end

  namespace :admin do
    resources :event_submissions, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    resources :event_submissions, only: [:index]
    post 'event_submissions/:id/validate', to: 'event_submissions#validate', as: 'validate_event_submission'
  end


  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
end





end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
  after_create :send_participation_email
  
  
  
  private

  def send_participation_email
    EventMailer.participation_email(event.user, user, event).deliver_now
  end

end

app/models/event.rb
class Event < ApplicationRecord
  
  belongs_to :admin, class_name: 'User', foreign_key: 'user_id'
  has_many :users, through: :attendances
  has_many :attendences
  validates_presence_of :start_date, :duration, :title, :description, :price, :location
  validates :duration, numericality: { only_integer: true, greater_than: 0 }, inclusion: { in: [5, 10, 15, 20, 25, 30, 60, 90, 120] }
  validates :title, length: { in: 5..140 }
  validates :description, length: { in: 20..1000 }
  validates :price, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 1000 }
  

end

app/models/event_submission.rb
class EventSubmission < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  after_create :send_welcome_email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :email, presence: true, uniqueness: true
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, foreign_key: :user_id
  has_many :events, through: :attendances
  has_many :attendances
  has_many :administered_events, class_name: 'Event', foreign_key: 'admin_id'

  enum role: { user: 0, admin: 1 }



  private

  def send_welcome_email
    UserMailer.welcome_email(self).deliver_now
  end





end

  

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin

def new
  @user = User.new
end
  def index
  @users = User.all 


  end

  





def edit_user
  @user = User.find(params[:id])
  # Logique pour la modification d'utilisateur
end

def update_user
  @user = User.find(params[:id])
  if @user.update(user_params)
    # Rediriger vers la liste des utilisateurs avec un message de succès
  else
    # Rediriger vers le formulaire de modification avec des erreurs
  end
end

 def destroy_user
  @user = User.find(params[:id])
  @user.destroy
  # Rediriger vers la liste des utilisateurs avec un message de succès

 end

 private

 def authenticate_admin
   # Vérifier si l'utilisateur est un administrateur
   # Rediriger vers la page de connexion si ce n'est pas le cas
 end


 def user_params

  # Paramètres autorisés pour la modification de l'utilisateur
 end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  
  def index
  
    @attendances = Attendance.all
  end
  def new
    @attendance = Attendance.new

  end

  def create
    @attendance = Attendance.new(attendance_params)
    @event = Event.find(params[:event_id])
    @attendance.event = @event
    @attendance.user = current_user
  
    if @attendance.save
      redirect_to @attendance, notice: 'Attendance was successfully created.'
    else
      render :new
    end
  end

  def edit
    @attendance = Attendance.find(params[:id])
  end
  def show
    @attendance = Attendance.find(params[:id])
  end
  def destroy
  end

private

def attendance_params
  params.require(:attendance).permit(:event_id) # Ajoutez d'autres attributs au besoin
end





end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def create
    @total = params[:total].to_d
    @session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [
        {
          price_data: {
            currency: 'eur',
            unit_amount: (@total*100).to_i,
            product_data: {
              name: 'Rails Stripe Checkout',
            },
          },
          quantity: 1
        },
      ],
      mode: 'payment',
      success_url: checkout_success_url + '?session_id={CHECKOUT_SESSION_ID}',
      cancel_url: checkout_cancel_url
    )
    redirect_to @session.url, allow_other_host: true
  end


  def success
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
  end

  def cancel
  end
end

app/controllers/event_submissions_controller.rb
class EventSubmissionsController < ApplicationController

 def index
  @event_submissions = EventSubmission.all
 end
 
 def show 
 end
 
 def edit
 end

 def update
 end




 def validate
  @event_submission = EventSubmission.find(params[:id])
  @event_submission.event.update(validated: true)
  @event_submission.destroy
  # Rediriger vers la liste des événements à valider avec un message de succès
 end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(event_params)
   
    @event.admin = current_user
    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end

  end

  def new
    @event = Event.new

  end

  def edit
    @event = Event.find(params[:id])
    
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    if @event.save!
      redirect_to events_path
    else
      render 'edit'
    end
    
  end

  def destroy
    @event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end
 
  private

  def set_event
    @event = Event.find(params[:id])
  end

def event_params
  params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location, :user_id)
end


  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit

   @user = user.find(params[:id])
  end
  def update
  @user = user.find(params[:id])
  if @user.update(user_params)
  redirect_to users_path
  else
  render 'edit'
  end
  end
  
  
  
 private
 def post_user
  

 end
 def user_params
   params.require(:user).permit(:email, :encrypted_password, :description, :first_name, :last_name)
  # Liste des attributs de l'utilisateur que vous autorisez à être mis à jour
 end
 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  
  @events = Event.all
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for_flash(type)
    case type
      when 'notice' then "alert-info"
      when 'success' then "alert-success"
      when 'error' then "alert-danger"
      when 'alert' then "alert-warning"
    end
  end



end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/event_submissions_helper.rb
module EventSubmissionsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/index.html.erb
<br><br>
<div class="container">
  <h1 class="text-center mt-4">Admin Page</h1>

  <div class="row mt-4">
    <% @users.each do |user| %>
      <div class="col-md-4 mb-4">
        <div class="card">
          <img src="<%= asset_path('admin.jpg') %>" class="card-img-top" alt="User Image">
          <div class="card-body">
            <%= form_for(user, url: admin_user_path(user), remote: true, method: :patch) do |f| %>
              <div class="mb-3">
                <%= f.label :email, class: "form-label" %>
                <%= f.text_field :email, class: "form-control" %>
              </div>

              <div class="mb-3">
                <%= f.label :role, class: "form-label" %>
                <%= f.select(:role, User.roles.keys.map { |w| [w.humanize, w] }, {}, class: "form-select") %>
              </div>

              <%= f.submit "Update", class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show" role="alert">
    <%= msg %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-light text-center py-3 mt-auto fixed-bottom">
  <div class="container">
    <span>© <%= Time.now.year %> Votre Société. Tous droits réservés.</span>
  </div>
</footer>

<script src="https:/

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-navbar" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="https://www.youtube.com/watch?v=XRzcnvwyrCg">eventbrite-zen</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <%= link_to "Accueil", root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Créer un Événement", new_event_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Tous les Événements", events_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Participations", attendances_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "conexion administrateur", admin_index_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "S'inscrire/Se connecter", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Mon Profil", edit_user_registration_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script  src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"> </script>
<%= stylesheet_link_tag 'style.css' %>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  <title>eventbrite</title>
  
  </head>

<body class="d-flex flex-column min-vh-100">

<%= render 'layouts/navbar' %>
<%= render 'layouts/flash' %>
<%= yield %>
<%= render 'layouts/footer' %>




</body>

</html>