config/routes.rb
Rails.application.routes.draw do
 devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :events
  resources :users, only: [:index, :edit, :update, :show]
  resources :orders, only: [:new, :create]
  resources :attendances
  # Defines the root path route ("/")
  root "welcome#index"
  

  namespace :admin do
    root to: 'admin#index'
  end
get "admin/index"


  namespace :admin do
    resources :users, only: [:index, :edit, :update, :destroy]
  end

  namespace :admin do
    resources :event_submissions, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    resources :event_submissions, only: [:index]
    post 'event_submissions/:id/validate', to: 'event_submissions#validate', as: 'validate_event_submission'
  end


  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
end





end

app/models/event.rb
class Event < ApplicationRecord
  
  belongs_to :admin, class_name: 'User', foreign_key: 'user_id'
  has_many :users, through: :attendances
  has_many :attendences
  validates_presence_of :start_date, :duration, :title, :description, :price, :location
  validates :duration, numericality: { only_integer: true, greater_than: 0 }, inclusion: { in: [5, 10, 15, 20, 25, 30, 60, 90, 120] }
  validates :title, length: { in: 5..140 }
  validates :description, length: { in: 20..1000 }
  validates :price, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 1000 }
  

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(event_params)
   
    @event.admin = current_user
    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end

  end

  def new
    @event = Event.new

  end

  def edit
    @event = Event.find(params[:id])
    
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    if @event.save!
      redirect_to events_path
    else
      render 'edit'
    end
    
  end

  def destroy
    @event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end
 
  private

  def set_event
    @event = Event.find(params[:id])
  end

def event_params
  params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location, :user_id)
end


  

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h1 class="card-title text-center mb-4">Créer un Événement</h1>

          <%= form_with(model: @event, local: true, html: { class: "form" }) do |form| %>
            <div class="mb-3">
              <%= form.label :start_date, class: "form-label" %>
              <%= form.datetime_field :start_date, class: "form-control" %>
            </div>

            <div class="mb-3">
              <%= form.label :duration, class: "form-label" %>
              <%= form.number_field :duration, class: "form-control" %>
            </div>

            <div class="mb-3">
              <%= form.label :title, class: "form-label" %>
              <%= form.text_field :title, class: "form-control" %>
            </div>

            <div class="mb-3">
              <%= form.label :description, class: "form-label" %>
              <%= form.text_area :description, class: "form-control", rows: 4 %>
            </div>

            <div class="mb-3">
              <%= form.label :price, class: "form-label" %>
              <%= form.number_field :price, class: "form-control" %>
            </div>

            <div class="mb-3">
              <%= form.label :location, class: "form-label" %>
              <%= form.text_field :location, class: "form-control" %>
            </div>

            <div class="d-grid">
              <%= form.submit "Créer l'Événement", class: "btn btn-primary btn-block" %>
            </div>
            
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/destroy.html.erb
<h1>Events_destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Events_edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<div class = "row card-event-parents"><% @events.each do |event| %>
  <div class="col-md-4 mb-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= event.title %></h5>
        <p class="card-text"><strong>Date :</strong> <%= event.start_date.strftime("%d/%m/%Y") %></p>
        <p class="card-text"><strong>Prix :</strong> <%= event.price %> €</p>
        <a href="<%= event_path(event) %>" class="btn btn-primary">Détails</a>
      </div>
    </div>
  </div>
<% end %>

app/views/events/new.html.erb
<%= render 'form' %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>
<p><%= @event.description %></p>
<p><strong>Date :</strong> <%= @event.start_date.strftime('%d/%m/%Y') %></p>
<p><strong>Prix :</strong> <%= @event.price %> €</p>
<p><%= button_to "Payment", checkout_create_path(total: "55"), class: "btn btn-primary", data: {turbo: false} %></p>

app/views/events/update.html.erb
<h1>Events_update</h1>
<p>Find me in app/views/events/update.html.erb</p>